// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/frostyard/site/templates/layouts"

func Downloads() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"max-w-4xl mx-auto px-4 py-12\"><h1 class=\"text-3xl font-bold text-slate-900 dark:text-slate-100 mb-8\">Downloads</h1><div class=\"space-y-6\"><div class=\"p-6 rounded-lg bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700\"><h2 class=\"text-xl font-semibold text-slate-900 dark:text-slate-100 mb-2\">Installation Media</h2><p class=\"text-slate-600 dark:text-slate-400 mb-4\">Our Live Installer works for all of our images.</p><a href=\"http://repository.frostyard.org/isos/snow-amd64.iso\" class=\"text-sky-600 dark:text-sky-400 hover:text-sky-500 dark:hover:text-sky-300\">Download ISO →</a></div><div class=\"p-6 rounded-lg bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700\"><h2 class=\"text-xl font-semibold text-slate-900 dark:text-slate-100 mb-2\">nbc (bootc installer)</h2><p class=\"text-slate-600 dark:text-slate-400 mb-4\">Install bootc container images to disk.</p><a href=\"https://github.com/frostyard/nbc/releases\" class=\"text-sky-600 dark:text-sky-400 hover:text-sky-500 dark:hover:text-sky-300\">View releases on GitHub →</a></div><div class=\"p-6 rounded-lg bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700\"><h2 class=\"text-xl font-semibold text-slate-900 dark:text-slate-100 mb-2\">Chairlift</h2><p class=\"text-slate-600 dark:text-slate-400 mb-4\">System management tool for SNOW Linux.</p><a href=\"https://github.com/frostyard/chairlift/releases\" class=\"text-sky-600 dark:text-sky-400 hover:text-sky-500 dark:hover:text-sky-300\">View releases on GitHub →</a></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Base(layouts.PageMeta{Title: "Downloads", SiteName: "Frostyard", Path: "/downloads/"}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
